import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-clinical-trial-site-budget-payment-reconciliation",
  "engine": "recovery",
  "title": "Clinical Trial Site Budget & Payment Reconciliation",
  "shortTitle": "Site Payment Recovery",
  "tagline": "Prove earned site revenue and recover every unpaid visit, milestone, and pass-through cost",
  "industry": "Clinical Research Site Finance",
  "uiPort": 4557,
  "apiPort": 5557,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Earned clinical-trial site revenue reconciled to sponsor and CRO payments",
  "valueNarrative": "Connect CTAs, budget grids, subject visits, EDC milestones, invoices, pass-through costs, holdbacks, and remittances.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "earnedAmount",
    "actualLabel": "Sponsor paid amount",
    "expectedLabel": "Site earned amount",
    "varianceLabel": "Unpaid site revenue",
    "direction": "expected-minus-actual",
    "finding": "Visit, milestone, pass-through, and contract evidence indicate earned but unpaid site revenue.",
    "actions": [
      "Reconcile subject activity to the CTA budget grid",
      "Validate milestones, screen failures, and pass-through evidence",
      "Issue or correct sponsor invoices",
      "Track sponsor response and cash receipt"
    ]
  }
},[
feature("cta-and-budget-grid-library","SPR01","CTA and budget-grid library","Reconcile cta and budget-grid library using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed cta and budget-grid library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("protocol-and-site-registry","SPR02","Protocol and site registry","Reconcile protocol and site registry using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed protocol and site registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("subject-enrollment-reconciliation","SPR03","Subject enrollment reconciliation","Reconcile subject enrollment reconciliation using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed subject enrollment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("visit-and-procedure-earnings","SPR04","Visit and procedure earnings","Reconcile visit and procedure earnings using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed visit and procedure earnings decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("screen-failure-payment-validation","SPR05","Screen-failure payment validation","Reconcile screen-failure payment validation using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed screen-failure payment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("milestone-payment-tracking","SPR06","Milestone payment tracking","Reconcile milestone payment tracking using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed milestone payment tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("start-up-fee-reconciliation","SPR07","Start-up fee reconciliation","Reconcile start-up fee reconciliation using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed start-up fee reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("pass-through-cost-recovery","SPR08","Pass-through cost recovery","Reconcile pass-through cost recovery using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed pass-through cost recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("holdback-and-retainage-control","SPR09","Holdback and retainage control","Reconcile holdback and retainage control using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed holdback and retainage control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("amendment-and-rate-effective-dates","SPR10","Amendment and rate effective dates","Reconcile amendment and rate effective dates using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed amendment and rate effective dates decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("invoice-generation-and-support","SPR11","Invoice generation and support","Reconcile invoice generation and support using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed invoice generation and support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("sponsor-payment-matching","SPR12","Sponsor payment matching","Reconcile sponsor payment matching using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed sponsor payment matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("payment-query-and-dispute-workflow","SPR13","Payment query and dispute workflow","Reconcile payment query and dispute workflow using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed payment query and dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("receivable-aging-and-forecasting","SPR14","Receivable aging and forecasting","Reconcile receivable aging and forecasting using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed receivable aging and forecasting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]}),
feature("study-profitability-analytics","SPR15","Study profitability analytics","Reconcile study profitability analytics using CTAs, budget grids, EDC visit data, CTMS milestones, screen failures, pass-through invoices, holdbacks, and remittances.","Produce a governed study profitability analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["sponsor","Sponsor / CRO","text","Nova Therapeutics"],["protocolSite","Protocol / Site","text","NTX-402 / Site 018"],["paidAmount","Sponsor Paid Amount","currency",486000],["earnedAmount","Site Earned Amount","currency",612500]],{amountField:"paidAmount",subjects:["Phase I oncology trial","Phase II rare disease study","Phase III vaccine study","Device feasibility study","Long-term follow-up protocol"]})
]);
